cmd_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o := /home/so-called-engineer/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/gpu/arm/t7xx/r15p0/.mali_kbase_strings.o.d  -nostdinc -isystem /home/so-called-engineer/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9.x/include -I/home/so-called-engineer/kernel/arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I/home/so-called-engineer/kernel/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/so-called-engineer/kernel/include/uapi -Iinclude/generated/uapi -include /home/so-called-engineer/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm64/mach-exynos/include -Iarch/arm64/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -fdiagnostics-show-option -Werror -DANDROID_VERSION=990000 -Os -Wno-maybe-uninitialized -mgeneral-regs-only -fno-pic -Wframe-larger-than=2064 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DTIMA_LKM_AUTH_ENABLED -Idrivers/gud/gud-exynos7420/MobiCoreKernelApi/include/ -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r15p0-00rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/t7xx/r15p0/platform/ -I/home/so-called-engineer/kernel/drivers/staging/android -Idrivers/gpu/arm/t7xx/r15p0 -Idrivers/gpu/arm/t7xx/r15p0/platform_dummy -I -Idrivers/gpu/arm/t7xx/r15p0/../../../base -I/home/so-called-engineer/kernel/include/linux -Idrivers/gpu/arm/t7xx/r15p0/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r15p0-00rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/t7xx/r15p0/platform/ -I/home/so-called-engineer/kernel/drivers/staging/android -Idrivers/gpu/arm/t7xx/r15p0 -Idrivers/gpu/arm/t7xx/r15p0/platform_dummy -Idrivers/gpu/arm/t7xx/r15p0/../../../base -I/home/so-called-engineer/kernel/include/linux -Idrivers/gpu/arm/t7xx/r15p0 -Idrivers/gpu/arm/t7xx/r15p0/platform/exynos -Idrivers/gpu/arm/t7xx/r15p0/backend/gpu    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_strings)"  -D"KBUILD_MODNAME=KBUILD_STR(mali_kbase)" -c -o drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.c

source_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o := drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.c

deps_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o := \
  drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.h \

drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o: $(deps_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o):
